### ISSUE TITLE
Improve grape-api test suite performance. 

### ISSUE THREAD

**Issue by towanda** [Devex/research#35]
Right now the test suite in grape-api takes about one minute and a half to run. Improving this performance would mean faster development cycles. 

Some things we could use to improve performance:

* Optimize the slowest tests (Using rspec --profile option which gives the top n slowest tests)
* Try to mock/stubs some calls to the database which are used in more than one place. For example, if in some controllers test we could mock the current user, we could save a lot of request to the database.
* Try using a database in memory, something like mysql memory tables, or any other solution to optimize db access.

**Comment by christofdamian** [comment]
+1
