### ISSUE TITLE
UI Prototype Builder

### ISSUE THREAD

**Issue by jezuhke** [Devex/research#36]
Tool to build quick prototypes using our existing UI elements. It will provide an interface where the user can drag and drop different UI elements and build an interface on the go.

## Expected Outcomes and Possible Results
The tool will be useful for kickstart meetings where we may want to test UI concepts, leveraging our Bootstrap & UI Toolbox setup. Other members of the company may be able to also use it, to brainstorm UI ideas.

## Steps & Tasks
- Adapt existing script (https://github.com/Vegetam/BootstrapPageGenerator) to Bootstrap 3
- Integrate our Toolbox
- Host somewhere (heroku?)
- Test

## Topics & Technologies
- Bootstrap
- JS
- https://github.com/Vegetam/BootstrapPageGenerator - needs a lot of work but is a good starting point

## Possible Follow-ups or Spin-offs
- Email templates?

**Comment by dsager** [comment]
@yaneq proposed that idea for the first hackathon as well, see #18 
I guess UI work just wasn't that popular back then :laughing:

**Comment by kamidar** [comment]
I like that this encourages maintaining and building out the UI toolbox.
