### ISSUE TITLE
Try functional object oriented programming approach

### ISSUE THREAD

**Issue by dsager** [Devex/research#42]
This interesting [blog post](https://medium.com/@bradurani/improving-your-web-app-with-functional-object-oriented-design-5218f9732b74) describes the concept of **functional object oriented design**. The main idea is to use classes to model *actions* instead of *things*:

> In an action-oriented web app, classes that do things (classes used by POSTs) are verbs: CreateUserCommand, ConfirmUserCommand, AddToCartCommand.

> Classes that read things (used by GETs) are grouped by the function they perform, not the objects they represent: HighestRatedProductsService, RecentlyPurchasedItemsService, ShoesByBrandService. 

> Each class has only a single public method, because it only does one thing.

## Expected Outcomes and Possible Results

This might result in better...
- ... code structure
- ... testability
- ... re-usability

## Steps & Tasks

- Pick some endpoints to work on (e.g. everything under `/jobs` or `/procurements/tenders`)
- Implement the new classes and add tests
- Compare it to the old code in terms of testability and structure

## Topics & Technologies

- Software Architecture / Design

## Possible Follow-ups or Spin-offs

- Slowly migrate our logic code to this approach.

**Comment by towanda** [comment]
+1

**Comment by christofdamian** [comment]
service classes I buy, but classes that only expose one ```execute``` method seems fishy. 
but still better than fat controllers
